config/routes.rb
Furfromhome::Application.routes.draw do
  devise_for :users

  resources :pets, except: [:index]
  get '/pets' => redirect('/')
  root to: 'pets#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :names, class_name: 'BreedName'
  has_many :pets

  def name
    names.first.name
  end

  def to_s
    name
  end
end

app/models/breed_name.rb
class BreedName < ActiveRecord::Base
  belongs_to :breed

  def to_s
    name
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  COLORS = %w[brown white black] #TODO: Add more colors
  # Assocations
  resourcify
  include Authority::Abilities
  belongs_to :author, class_name: 'User'
  belongs_to :breed
  belongs_to :user
  geocoded_by :location

  # Scopes
  scope :has_location,  -> { where "location IS NOT NULL" }
  scope :has_photo,     -> { where "photo_url IS NOT NULL" }
  scope :unreturned,    -> { where returned_to_owner: false }
  scope :listing_type,  -> ltype    { where listing_type: ltype }
  scope :breed_id,      -> breed_id { where breed_id: breed_id }
  scope :animal,        -> species  { where cached_species: species.downcase }
  scope :color,         -> color    { where color: color }
  scope :gender,        -> gender   { where gender: gender }
  scope :missing_since, -> day      { where "missing_since_found_at > ?", day }
  scope :source,        -> source   { where scraping_script: source }

  # Validations
  validates :location, presence: true
  validates :listing_type, inclusion: { in: ['lost', 'found'] }
  validates :gender, inclusion: { in: ['male', 'female'] }

  # Callbacks
  after_validation :geocode, if: :location_changed?
  before_save :cache_species

  # Methods
  def to_s
    name || breed || 'Pet'
  end

  private

  def cache_species
    self.cached_species = breed.species if breed
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Assocations
  rolify
  include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :pets, foreign_key: :author_id

  # Callbacks
  after_save :invalidate_devise_cache

  # Methods
  def self.serialize_from_session(key, salt)
    single_key = key.is_a?(Array) ? key.first : key
    Rails.cache.fetch("user:#{single_key}") { User.find(single_key) }
  end

  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params)
  end

  private
  def invalidate_devise_cache
    Rails.cache.delete("user:#{id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_devise_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:email, :password, :password_confirmation)                                  }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :first_name, :last_name, :phone, :password, :password_confirmation, :avatar_url) }
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pet, only: [:show, :new, :edit, :update, :destroy]
  before_action 'authorize_action_for @pet', except: [:index, :show, :new, :create]
  has_scope :has_location, default: true, type: :boolean
  has_scope :listing_type
  has_scope :missing_since
  has_scope :source
  has_scope :breed_id
  has_scope :animal
  has_scope :color
  has_scope :gender
  has_scope :page, default: 1
  has_scope :near

  def index
    @pets = apply_scopes(Pet).all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @pet = current_user.pets.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @pet.attributes = pet_params
    authorize_action_for @pet
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = params[:id] ? Pet.find(params[:id]) : Pet.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :color, :age, :weight, :markings, :gender, :collar, :collar_description, :chipped, :injured,
                                  :listing_type, :missing_since_found_at, :location, :latitude, :longitude, :description,
                                  :returned_to_owner, :scraping_script, :scraped_feed, :source_url, :breed_id, :user_id, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title = content_for?(:title) ? yield(:title) : "Fur From Home - Find your lost pets"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = filepicker_js_include_tag
    = csrf_meta_tags

    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-status-bar-style" content="black"
    meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'
  body[class="#{ params[:controller].parameterize } #{params[:action]}#{" " + @body_class if @body_class.present?}"]
    #viewport

      = render partial: "shared/menu" unless @no_menu
      
      #page
        = render partial: "shared/header"
        #body

          - if notice
            p.alert.alert-success
              = notice

          - if alert
            p.alert
              = alert

          = yield
        
          = render partial: "shared/footer"

app/views/pages/home.html.slim
= 'home.html.slim'

app/views/pages/terms.html.slim
p #TODO: Put in terms

app/views/pets/_card.html.slim
.card[class="card-#{pet.listing_type if pet.listing_type}"]
  = link_to pet do

    - if pet.photo_url.present?
      = filepicker_image_tag(pet.photo_url, w: 250, h: 200, fit: 'crop', class: "img")
    - else
      = image_tag "/assets/profile-default-dog.png"

    - if pet.name.present?
      h2== "&ldquo;#{pet.name}&rdquo;"

    - if pet.color || pet.gender || pet.breed
      p
        = "#{pet.color.capitalize}" if pet.color
        = " #{pet.gender.capitalize}" if pet.gender
        = " #{pet.breed}" if pet.gender


    p.ss-search
      = "#{pet.listing_type.capitalize} at #{pet.location} #{time_ago_in_words(pet.missing_since_found_at)} ago"

  .actions
    = link_to 'Edit', edit_pet_path(pet), class: "ss-icon" if current_user && current_user.can_update?(pet)
    = link_to 'Delete', pet, confirm: 'Are you sure?', method: :delete, class: "ss-icon" if current_user && current_user.can_delete?(pet)

app/views/pets/_form.html.slim
- @no_menu = true

= simple_form_for @pet, html: { class: 'form-horizontal' } do |f|
  - if @pet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"
      ul
        - @pet.errors.full_messages.each do |message|
          li = message

  = f.input :listing_type, collection: [:found, :lost], selected: :found, label: "Animal was"
  = f.input :missing_since_found_at, as: :string, input_html: { class: "datepicker" }, label: "Found on"
  .control-group
    = f.label :photo_url, "Upload photo:", class: "control-label"
    .controls
      .pull-right
        = filepicker_image_tag f.object.photo_url, w: 100, h: 100, fit: 'clip' if f.object.photo_url
      = f.filepicker_field :photo_url, onchange: "$('#pet_photo_url').val(arguments[0].fpfile.url)"
      = f.input :photo_url, as: :hidden
  = f.input :location
  .control-group
    label.control-label Animal
    .controls= select_tag :animal, options_for_select(Breed.uniq.pluck(:species), params[:animal]), prompt: 'Kind of animal'
  = f.association :breed, prompt: 'Unknown', wrapper_html: { class: "#{'hidden' unless params[:animal]}" }
  = f.input :gender, collection: [:male, :female], prompt: "Select Gender"
  = f.input :color
  = f.input :markings, placeholder: "None"
  = f.input :age, placeholder: "Unknown"
  = f.input :weight, placeholder: "Unknown"
  -# = f.input :latitude
  -# = f.input :longitude
  = f.input :name, placeholder: "Unknown"
  = f.input :description
  = f.input :collar
  = f.input :collar_description, placeholder: "Color or pattern", wrapper_html: { class: "#{'hidden' unless @pet.collar == true}" }
  = f.input :chipped, label: "Microchipped"
  = f.input :injured

  .form-actions
    = f.button :submit

app/views/pets/_list_item.html.slim
li
  - if pet.photo_url.present?
    = filepicker_image_tag(pet.photo_url, w: 50, h: 50, fit: 'crop', class: "img")
  - else
    = image_tag "/assets/profile-default-dog.png"

  p
    =link_to pet.name, pet

app/views/pets/edit.html.slim
.container

  .column-slim
    p.page-actions = link_to "Back", pets_path, class: "ss-navigateleft"

    .page

      h2.page-title Editing #{ @pet.name.present? ? @pet.name : "pet" }

      == render 'form'

app/views/pets/index.html.slim
.results
  - if @pets.any?
    ul.list-cards.list-simple
      - @pets.each do |pet|
        li= render "card", pet: pet
  - else
    .empty Sorry, we didn't find any pets that match that description

= will_paginate @pets

app/views/pets/new.html.slim
.container

  .column-slim

    p.page-actions = link_to "Back", pets_path, class: "ss-navigateleft"

    .page
      h2.page-title Let's get this pet home

      == render 'form'

app/views/pets/show.html.slim
-if notice
  p#notice= notice

.container


  p.page-actions = link_to "Back", :back, class: "ss-navigateleft"

  .page

    .actions
      = link_to 'Edit', edit_pet_path(@pet), class: "ss-icon" if current_user && current_user.can_update?(@pet)
      = link_to 'Delete', @pet, confirm: 'Are you sure?', method: :delete, class: "ss-icon" if current_user && current_user.can_delete?(@pet)

    .row

      .span8

        - if @pet.name.present?
          h2== "&ldquo;#{@pet.name}&rdquo;"

        h3
          = "#{@pet.color.capitalize}" if @pet.color
          = " #{@pet.gender.capitalize}" if @pet.gender
          = " #{@pet.breed}"

        p.ss-search
          = "#{@pet.listing_type.capitalize} at #{@pet.location} #{time_ago_in_words(@pet.missing_since_found_at)} ago"

        - if @pet.description
          p
            = @pet.description

        hr

        section.meta

          dl
            - if @pet.age?
              dt Age: 
              dd= @pet.age

            - if @pet.weight?
              dt Weight:
              dd= "#{@pet.weight} pounds"

            - if @pet.markings.present?
              dt Markings: 
              dd= @pet.markings

            - if @pet.collar
              dt Collar:
              dd= @pet.collar_description
            
            dt Microchipped: 
            dd= @pet.chipped ? "Yes" : "No"

            dt Injured: 
            dd= @pet.injured ? "Yes" : "No"

            dt Returned to owner: 
            dd= @pet.returned_to_owner ? "Yes" : "No"

      .span4

        section
          p = filepicker_image_tag @pet.photo_url, w: 400, h: 360, fit: 'crop' if @pet.photo_url

          p = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@pet.latitude}%2C#{@pet.longitude}"

        section
          - nearby_pets = @pet.nearbys(5).try(:limit, 5)
          - if nearby_pets.any?
            h3 Nearby pets
            ul.list-pets
              - nearby_pets && nearby_pets.each do |pet|
                = render "list_item", pet: pet

app/views/shared/_footer.html.slim
footer

  ul.list-inline
    - if !user_signed_in?
      li = link_to('Register', new_user_registration_path)
      li = link_to('Sign in', new_user_session_path)
    - else
      li = link_to('Profile', edit_user_registration_path)
      li = link_to('Sign out', destroy_user_session_path, method: :delete)

app/views/shared/_header.html.slim
#close-mask
header.site-header

  - unless @no_menu
    .trigger.btn.ss-search Search

  = link_to 'Add a Pet', new_pet_path, class: "btn new-pet-link pull-right ss-plus"

  h1.logo
    = link_to "Fur from home", "/"

app/views/shared/_menu.html.slim
#menu
  .scrollable
    header Search
    = form_tag root_path, method: :get, id: "pets-index" do
      ul.form-search.sidebar
        li= text_field_tag :near,          params[:near], placeholder: "Near location"
        li= select_tag     :listing_type,  options_for_select([:lost, :found], params[:listing_type]), prompt: "Lost and found"
        li= text_field_tag :missing_since, params[:missing_since], placeholder: "Missing since"
        li= select_tag :animal,            options_for_select(Breed.uniq.pluck(:species), params[:animal]), prompt: 'Any animal'
        li= select_tag :color,             options_for_select(Pet::COLORS, params[:color]), prompt: 'Any color'
        li= select_tag :gender,            options_for_select([:male, :female], params[:gender]), prompt: 'Any gender'
        -#TODO: Make dynamic based on animal
        li= select_tag :breed_id,          options_from_collection_for_select(BreedName.select(:id, :name), 'id', 'name', params[:breed_id]), prompt: 'Any breed', class: "chosen"
        li= submit_tag "Search", name: nil, class: "btn btn-primary"